---
# Default namespace
apiVersion: v1
kind: Namespace
metadata:
  name: workspace
  annotations:
    linkerd.io/inject: enabled
  labels:
    # Epinio app namespaces are targeted by reflector via reflection-*-namespaces-selector
    app.kubernetes.io/component: "epinio-namespace"

---
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: workspace
  namespace: workspace
imagePullSecrets:
- name: registry-creds
