apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: epinio-staging
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.epinio.tag }}
  name: epinio-stage-scripts-jammy
  namespace: {{ .Release.Namespace }}
data:
  builder: "paketobuildpacks/builder-jammy-*:*"
  userID: "1001"
  groupID: "1000"
  env: |-
    CNB_PLATFORM_API: "0.11"
  base: epinio-stage-scripts
  {{- with .Values.server.stagingWorkloads }}
  staging-values.json: |-
    {{- toJson . | nindent 4 }}
  {{- end }}
