apiVersion: application.epinio.io/v1
kind: AppChart
metadata:
  namespace: {{ .Release.Namespace }}
  name: stateful
  labels:
    app.kubernetes.io/component: epinio
    app.kubernetes.io/instance: stateful
    app.kubernetes.io/name: epinio-stateful-app-chart
    app.kubernetes.io/part-of: epinio
    app.kubernetes.io/version: {{ default .Chart.AppVersion .Values.image.epinio.tag }}
spec:
  shortDescription: Epinio stateful deployment
  description: Epinio stateful support chart for application deployment
  helmChart: {{ .Values.appChart.stateful | quote }}
  settings:
    appListeningPort:
      type: 'integer'
      minimum: '0'
