{{- if not .Values.grafanaCloud.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-cloud-observability.tokenSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-cloud-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ required "grafanaCloud.token is required" .Values.grafanaCloud.token | quote }}
{{- end }}
