{{- if and .Values.mcp.enabled .Values.mcp.ingress.enabled (or .Values.ingress.enabled (not (hasKey .Values.ingress "enabled"))) }}
{{- if .Values.certManager.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: epinio-mcp
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ include "epinio-mcp-hostname" . | quote }}
  issuerRef:
    kind: ClusterIssuer
    name: {{ default .Values.global.tlsIssuer .Values.global.customTlsIssuer | quote }}
  secretName: epinio-mcp-tls
{{- else }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: epinio-mcp-tls
  namespace: {{ .Release.Namespace }}
stringData:
  ca.crt: {{ default .Values.certManager.epinio.ca .Values.certManager.mcp.ca | quote }}
  tls.key: {{ default .Values.certManager.epinio.key .Values.certManager.mcp.key | quote }}
  tls.crt: {{ default .Values.certManager.epinio.cert .Values.certManager.mcp.cert | quote }}
{{- end }}
{{- end }}
