{{- range .Values.epinio.routes }}
---
apiVersion: "cert-manager.io/v1"
kind: Certificate
metadata:
  name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  secretName: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id "-tls") }}
  dnsNames:
  - {{ .domain }}
  issuerRef:
    name : {{ $.Values.epinio.tlsIssuer | quote }}
    kind: ClusterIssuer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    {{- include "epinio-application.labels" $ | nindent 4 }}
spec:
  {{- with $.Values.epinio.ingress }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ .domain | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "epinio-truncate" (print $.Values.epinio.appName) }}
                port:
                  number: 8080
            path: {{ .path | quote }}
            pathType: ImplementationSpecific
  tls:
    - hosts:
      - {{ .domain | quote }}
      secretName: {{ include "epinio-truncate" (print $.Values.epinio.appName "-" .id "-tls") }}
{{- end }}
